server:
  port: 8090

spring:
  application:
    name: PaymentService
  #Database Details
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: user
    password: password
  #JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL



#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
