#Server Port
server:
  port: 8082

#Application Name
spring:
  application:
    name: UserService

#MongoDb
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms_buyerservice_db

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true