server:
  port: 8081

spring:
  application:
    name: ServiceGateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      #Routes Configuration
      routes:
        #Auth-Service
        - id: auth-service
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: AuthFilter

        #User-Service
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/v1/buyers/**
          filters:
            - name: AuthFilter

        #Notification-Service
        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: AuthFilter

        #Order-Service
        - id: order-service
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/orders/**

        #Seller-Service
        - id: seller-service
          uri: lb://SELLERSERVICE
          predicates:
            - Path=/api/v1/sellers/**
          filters:
            - name: AuthFilter

        #Product-Service
        - id: product-service
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: AuthFilter
  main:
      allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true