server:
  port: 8084

spring:
  application:
    name: NotificationService
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true