server:
  port: 8084

#Custom Properties For RabbitMQ Configuration
consumer:
  purchase-order:
    queue-name: purchaseOrderQueue


spring:
  application:
    name: NotificationService

  #MongoDb
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ms_authservice_db

  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 2s

  #Mail Configuration Properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: testmail8293@gmail.com
    password: ghcu rety jzia ybzu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

